// Copyright (c)2021 Quinn Michaels. All Rights Reserved

module.exports = (input, process=true) => {
  // global replace
  let firstpass = input.replace(/Indra-Varuṇa|Indra-Soma|Maghavan|Savitar|Viṣṇu/g, 'Indra')
            .replace(/Indra, Etc|Varuṇa|Mitra-Indra/g, 'Indra')
            .replace(/Indra and Others/g, 'Indra')
            .replace(/Śakra/g, 'Indra')
            .replace(/Soma and Others/g, 'Soma')
            .replace(/Viśvedevas/g, 'Devas')
            .replace(/Dyaus/g, 'Devas')
            .replace(/Asura/g, 'Devas')
            .replace(/Agni, Maruts/g, 'Agni')
            .replace(/Vāyu/g, 'Soma')
            .replace(/Rudra/g, 'Soma')
            .replace(/Bṛhaspati/g, 'Soma')
            .replace(/Vasus/g, 'Devas')
            .replace(/Mitra, Varuṇa/g, 'the Devas')
            .replace(/Varuṇa, Mitra, Aryaman/g, 'Devas')
            .replace(/Various Deities\./g, 'Devas.')
            .replace(/Maruts/g, 'Devas')
            .replace(/Some Pavamana/g, 'Indu')
            .replace(/Some Pavamana/g, 'Indu')
            .replace(/Soma Pavanana/g, 'Indu')
            .replace(/Soma Pavamana/g, 'Indu')
            .replace(/VṢoma Pavamana/g, 'V. Indu')
            .replace(/Brahmaṇaspati/g, 'Soma')
            .replace(/Soma-Soma/g, 'Soma and SomaDeva')
            .replace(/Indra-Indra/g, 'Indra and IndraDeva')
            .replace(/Indra-Agni/g, 'Indra and Agni')
            .replace(/Pavamana/g, 'Indu')
            .replace(/HYMN V Āprīs./g, 'HYMN V Indu.')
            .replace(/Āprīs/g, 'Indu')
            .replace(/Aśvins/g, 'Indra')
            ;

  if (!process) return firstpass;

  const titleStr = /<h3.+>(.+)<\/h3>/g;
  const nextStr = /<a href="rv(.+)\.htm">Next<\/a>/i;
  const prevStr = /<a href="rv(.+)\.htm">Previous<\/a>/i;
  const bkiStr = /<a href="rvi(.+)\.htm">(.+)<\/a>/i;
  const keyStr = /<a href="\.\.\/rvsan\/rv(.+)\.htm">Sanskrit<\/a>/i;

  const title = titleStr.exec(firstpass)[1].trim();

  const prv = prevStr.test(firstpass) ? prevStr.exec(firstpass)[1].trim() : false; // previous page
  const nxt = nextStr.test(firstpass) ? nextStr.exec(firstpass)[1].trim() : false; // next page
  const bki = bkiStr.test(firstpass) ? bkiStr.exec(firstpass)[1].trim() : false; // book index
  const key = keyStr.test(firstpass) ? keyStr.exec(firstpass)[1].trim() : false;

  const cleaned = firstpass.split('</h3>')[1].split('<HR>')[0].trim().replace(/<\/?p>/gi, '')
    .replace(/^\d+\.?\s?/g, '\np:')
    .replace(/<br>\s?\d+\.?\s?/g, '\np:')
    .replace(/(\.)<br>(.+)/, '$1\np:$2\r')
    .replace(/<br>\s?/g, ' ')
    .replace(/(our|the|guidest) sacrifice/g, '$1 offering')
    .replace(/(\b)heaven(\b)/g, '$1Heaven$2')
    .replace(/(\b)earth(\b)/g, '$1Earth$2')
    .replace(/(\b)firmament(\b)/g, '$1Firmament$2')
    .replace(/Steed The/g, 'Steed. The')
    .replace(/race Of/g, 'race of')
    .replace(/, Well/g, ', well')
    .replace(/, Be/g, ', be')
    .replace(/, For/g, ', for')
    .replace(/, And/g, ', and')
    .replace(/, To/g, ', to')
    .replace(/, A /g, ', a ')
    .replace(/, As /g, ', as ')
    .replace(/, With/g, ', with')
    .replace(/, Free/g, ', free')
    .replace(/, Accept/g, ', accept')
    .replace(/, Thus/g, ', thus')
    .replace(/, Attained/g, ', attained')
    .replace(/, She/g, ', she')
    .replace(/, That/g, ', that')
    .replace(/, When/g, ', when')
    .replace(/, Whose/g, ', whose')
    .replace(/up Our/g, 'up our')
    .replace(/, Show/g, ', show')
    .replace(/, The/g, ', the')
    .replace(/, Or/g, ', or')
    .replace(/, Most/g, ', most')
    .replace(/, Make/g, ', make')
    .replace(/, Foundest/g, ', found')
    .replace(/, Lasting/g, ', lasting')
    .replace(/, Vouchsafe/g, ', vouchsafe')
    .replace(/, Have/g, ', have')
    .replace(/, Who/g, ', who')
    .replace(/, By/g, ', by')
    .replace(/, Givey/g, ', give')
    .replace(/, Laid/g, ', laid')
    .replace(/, Him/g, ', him')
    .replace(/, Wherein/g, ', wherein')
    .replace(/, Like/g, ', like')
    .replace(/, Worship/g, ', worship')
    .replace(/, Present/g, ', present')
    .replace(/, Decking/g, ', decking')
    .replace(/, Is/g, ', is')
    .replace(/once Unto/g, 'once unto')
    .replace(/man Sings/g, 'man sings')
    .replace(/those Fair/g, 'those fair')
    .replace(/about Verily/g, 'about verily')
    .replace(/grass At/g, 'grass, at')
    .replace(/like A /g, 'like a ')
    .replace(/pour We/g, 'pour. We')
    .replace(/once Unto /g, 'once Unto ')
    .replace(/prayer Bringing/g, 'meditation bringing')
    .replace(/sacrificial food/g, 'sacred food')
    .replace(/thou Destruction/g, 'thou destruction')
    .replace(/sacrificial ladle/g, 'ceremonial ladle')
    .replace(/sacrifice with Gods/g, 'offerings with Devas')
    .replace(/In sacrifices/g, 'In offerings')
    .replace(/grace of sacrifice/g, 'grace of offering')
    .replace(/To (.+) sacrifice/g, 'To $1 offerings')
    .replace(/solemn sacrifice/g, 'solemn offering')
    .replace(/works to sacrifice/g, 'works of offering')
    .replace(/(\b)slaying(\b)/g, '$1subduing$2')
    .replace(/(\b)slays(\b)/g, '$1subdues$2')
    .replace(/(\b)slay(\b)/g, '$1subdue$2')
    .replace(/, Urged onward by Bṛhaspati,/gi, '')
    .replace(/each who sacrifices/gi, 'each who make offerings')
    .replace(/(\b)destroyed(\b)/g, '$1conquered$2')
    .replace(/<A HREF=".+">(.+)<\/A>/gi, '$1')
    .replace(/, the sacrificer cries aloud/gi, '')
    .replace(/, minister of sacrifice/gi, '')
    .replace(/Agni, the perfect sacrifice/gi, 'Agni,')
    .replace(/, plenty waxing day by day/gi, '')
    .replace(/, the God/g, '')
    .replace(/, the chosen Priest, God/g, '')
    .replace(/ bringing thee reverence, we come/g, '.')
    .replace(/Ruler of sacrifices, guard of Law eternal/g, 'Guard of Law Eternal')
    .replace(/, Far-spreading/g, '')
    .replace(/, sapient-minded Priest/g, '')
    .replace(/approach Your/g, 'approach your')
    .replace(/, Have ye obtained your might power/g, '.')
    .replace(/, may bright Sarasvat&#299; desire/g, '.')
    .replace(/, Assuming sacrificial names/g, '')
    .replace(/, with awful aids, O awful One/g, '')
    .replace(/, rich in cattle/g, '')
    .replace(/, to the prayers/g, '')
    .replace(/him The/g, 'him. The')
    .replace(/oil, Bring/g, 'oil. Bring')
    .replace(/, and free from terror aided thee,/g, '')
    .replace(/The priests/g, 'The Monks')
    .replace(/born Sustainer/g, 'born. Sustainer')
    .replace(/bears The gift: the ladle is his mouth/g, 'bears the gift')
    .replace(/lord of sacrificial gifts/g, 'lord of sacred gifts')
    .replace(/, let no man hurt our bodies, keep Slaughter far from us, for thou canst/g, '')
    .replace(/: Manu appointed thee as Priest/g, '')
    .replace(/for sacrifice this/g, 'for offering this')
    .replace(/, B&#7771;haspati,/g, ',')
    .replace(/, O God,/g, ',')
    .replace(/the wise invoking Priest/g, 'the wise invoking Monk')
    .replace(/drink with thy tongue The meath in/g, 'drink in')
    .replace(/#151;a Power that none deceives&#151;/g, '')
    .replace(/, the Vṛtra-slayer, comes,/g, ' comes')
    .replace(/Ordained by Manu as our Priest, thou sittest, Agni, at each rite: /g, '')
    .replace(/Iḷā, Sarasvatī, Mahī, three Goddesses who bring delight, be/g, 'Be')
    .replace(/p:Inciter of all pleasant songs, inspirer of all gracious thought, Sarasvatī accept our rite/gi, '')
    .replace(/p:Sarasvatī, the mighty flood,—she with her light illuminates, she brightens every pious thought.\s+?/gi, '')
    .replace(/, Wast born together with the Dawns/gi, '')
    .replace(/benevolence Of/g, 'benevolence. Of')
    .replace(/Even Kak&#7779;&#299;v&#257;n Au&#347;ija./g, '')
    .replace(/O BR&#256;HMA&#7750;ASPATI, make/g, 'Make')
    .replace(/Soma glorious,/g, 'Soma glorious.')
    .replace(/Preserve us, Brahma&#7751;aspati./g, '.')
    .replace(/Brahma&#7751;aspati, and/g, '')
    .replace(/Household Priest/g, 'Household Monk')
    .replace(/course of sacrifice/g, 'course of offering')
    .replace(/he Stirs/g, 'he stirs')
    .replace(/whom no sacrifice/g, 'whom no offering')
    .replace(/: Our voice of praise goes to the Gods/g, '')
    .replace(/, and awful in their form/g, '')
    .replace(/, devourers of their foes:/g, ',')
    .replace(/ Was made by singers with their lips/g, '')
    .replace(/As ministering Priests they held, b/g, 'B')
    .replace(/, crush the fiends: Childless be the devouring ones./g, '.')
    .replace(/best Of/g, 'best of')
    .replace(/, as a God,/g, '')
    .replace(/, distributer of wondrous bounty and of wealth,/g, '.')
    .replace(/, Giving/g, ', giving')
    .replace(/, hither bring to us the willing Spouses of the Gods,/g, '')
    .replace(/, hither bring their Spouses/g, '')
    .replace(/p:Spouses of Heroes, Goddesses, with whole wings may they come to us With great protection and with aid./g, '')
    .replace(/ even from the place whence Viṣṇu strode/g, '.')
    .replace(/forth Estab/g, 'forth estab')
    .replace(/invoke To/g, 'invoke to')
    .replace(/, strike V&#7771;tra down, ye bounteous Gods/g, '.')
    .replace(/ Be swift, ye Gods,/g, ' be swift')
    .replace(/&#151;Soma thus hath told me&#151;/g, ' ')
    .replace(/, and Agni, he who blesseth all/g, ' ')
    .replace(/, Agni;/g, ',')
    .replace(/, Speed forth this sacrifice/g, '. Speed forth this offering')
    .replace(/, Goddesses,/g, '')
    .replace(/Waters in the Waters/g, 'Waters. In the Waters')
    .replace(/heal . The/g, 'heal. The')
    .replace(/harm, So/g, 'harm. So')
    .replace(/; the Gods Shall k/g, '. K')
    .replace(/, what God among Immortals/g, '')
    .replace(/, ye stretch wide jaws, O Sacrificial Implements, L/g, ' l')
    .replace(/Destroy this ass, /g, '')
    .replace(/, whose jaws are strong/g, '')
    .replace(/, great deeds are thine/g, '')
    .replace(/, the powerful: Do thou/g, '')
    .replace(/wake: Do/g, 'wake.\np:Do')
    .replace(/treasures A/g, 'treasures. A')
    .replace(/, Travels,/g, ', travels,')
    .replace(/, O Daughter of the Sky/g, '')
    .replace(/, Red-hued and like a dappled mare/g, '')
    .replace(/, O immortal Dawn,/g, '')
    .replace(/, a God among the Gods/g, '')
    .replace(/Whatever blessing, /g, '')
    .replace(/, thou wilt grant unto thy worshipper, that,/g, ' ')
    .replace(/, dispeller of the night/g, '')
    .replace(/my prayer/g, 'me meditation')
    .replace(/, of holy strength/g, '')
    .replace(/, and foe-destroying Varuṇa/g, '')
    .replace(/, void of guile, bearers/g, '')
    .replace(/, changing shape like serpents, fearless/g, '')
    .replace(/, may bright Sarasvatī desire/g, '')
    .replace(/, accept the sacred draught/g, ', accept the sacred draught.')
    .replace(/: Neglect us not, come hitherward/g, '')
    .replace(/, whose succour never fails/g, '')
    .replace(/viands/g, 'offerings')
    .replace(/, O Śatakratu/g, '')
    .replace(/lauds So/g, 'lauds. So')
    .replace(/, wherein all manly powers abide/g, '')
    .replace(/, the victor's ever-conquering wealth/g, '')
    .replace(/, drinking deepest draughts of Soma/g, '')
    .replace(/, like an ocean swells/g, '')
    .replace(/, that he may drink the Soma juice/g, '')
    .replace(/our prayer/g, 'our meditation')
    .replace(/drink-offerings/g, 'water-offerings')
    .replace(/, in battles hearer of our cry/g, '')
    .replace(/, Son of Kuśika/g, '')
    .replace(/The wily Śuṣṇa, /g, '')
    .replace(/, thou didst burst the cave of Vala rich in cows/g, '')
    .replace(/The Gods came pressing to thy side/g, '')
    .replace(/, the never-conquered conqueror/g, '')
    .replace(/, his saving succours, never fail/g, '')
    .replace(/Crusher of forts, the young, the wise, of strength unmeasured, was he born\./g, '')
    .replace(/Gods/g, 'Devas')
    .replace(/, burn up our enemies whom fiends protect/g, '')
    .replace(/, Śatakratu, drankest this and wast the Vṛtras’ slayer; thou H/g, 'h')
    .replace(/, Śatakratu, thee, yea/g, '')
    .replace(/In mighty battle we/g, 'We')
    .replace(/, Indra in lesser fight/g, '')
    .replace(/the Soma-drinker/g, 'Soma')
    .replace(/ juice outpoured/g, '')
    .replace(/, wast born to drink the Soma juice/g, '')
    .replace(/ these quick Somas enter thee: May/g, '')
    .replace(/, and our lauds/g, '')
    .replace(/As a good cow to him who milks, we/g, 'We')
    .replace(/, drink of Soma; Soma-drinker thou/g, '')
    .replace(/Whether the men who mock us say, Depart unto another place, /g, '')
    .replace(/Thouhelpest/g, 'Thou helpest')
    .replace(/ in fight, that/g, '')
    .replace(/ who pours the juice, Yea/g, '')
    .replace(/, the Somas mingled with the curd/g, '')
    .replace(/, the breakers down of what is firm/g, '')
    .replace(/, the blameless/g, '')
    .replace(/: He burst the mountain for the kine/g, '')
    .replace(/Unclose, o/g, 'O')
    .replace(/or your sake f/g, '')
    .replace(/with missile-darting /g, 'with ')
    .replace(/may We/g, 'may we')
    .replace(/, stimulate thereto us emulously fain for wealth, and glorious/g, '')
    .replace(/ in cattle and/g, '')
    .replace(/, failing not/g, '')
    .replace(/ bestowing thousands/g, '')
    .replace(/, that Śakra may take pleasure/g, '')
    .replace(/Tvaṣṭar I call, the earliest born, the wearer of all forms at will: /g, '')
    .replace(/God,/g, 'Deva,')
    .replace(/ Vāyu, and Mitra's splendours, drink/g, 'Deva,')
    .replace(/the pleasant Soma juice/g, 'Soma')
    .replace(/ drink in solemn/g, 'solemn')
    .replace(/ withDeva/g, 'with Deva')
    .replace(/The Kaṇvas/g, 'We')
    .replace(/Indra, Vāyu, Bṛhaspati, Mitra, Agni, Pūṣan, Bhaga, Ādityas, and the Marut host/g, 'Invoke Indu, Indra, Agni, Soma, Pūṣan, Bhaga, and all the Devas')
    .replace(/, with their Dames: Make them drink meath/g, '')
    .replace(/praisesolemn/g, 'prase solemn')
    .replace(/these juices/g, 'these offerings')
    .replace(/The sons of Kaṇva fain for help adore thee, h/g, 'H')
    .replace(/ to the Soma draught/g, 'H')
    .replace(/; and worship them/g, '')
    .replace(/To drink the Soma,/g, 'Soma,')
    .replace(/O INDRA drink the Soma juice /g, 'O Indra ')
    .replace(/; let the cheering drops Sink deep within, which settle there/g, '')
    .replace(/Drink from the Purifier's cup, /g, '')
    .replace(/sanctify The/g, 'sanctify the')
    .replace(/O Neṣṭar, with thy Dame a/g, 'A')
    .replace(/Ṛtu drink/g, 'Ṛtu')
    .replace(/Drink Soma after the /g, '')
    .replace(/, from the Brāhmaṇa's bounty:/g, ',')
    .replace(/Mitra, Varuṇa, ye whose ways are firm—a Power that none deceives—, with/g, 'With')
    .replace(/The Soma-pressers, fain for wealth, p/, 'P')
    .replace(/(\b)the God(\b)/g, '$1the Deva$2')
    .replace(/ fain would drink, Wealth-giver, from the Neṣṭar's bowl. Haste, give your offering, and depart/g, '')
    .replace(/Drink ye the meath, O Aśvins bright with flames, w/g, 'W')
    .replace(/, through the house-fire, thou/g, '')
    .replace(/Maruts, with Ṛtu; s/g, 'S')
    .replace(/As we this fourth time, /g, '')
    .replace(/ hither to drink the Soma draught— Those/g, '')
    .replace(/ere are the grains bedewed with oil: h/g, '')
    .replace(/To every draught of pressed-out juice /g, '')
    .replace(/to drink the Soma/g, '')
    .replace(/Fulfil, all our wish with horses and with kine: /g, '')
    .replace(/, to he draught we pour. We call thee when the juice is shed/g, '')
    .replace(/, Indra juice/gi, ' water')
    .replace(/ are the drops of Soma juice expressed/gi, '')
    .replace(/: thereof Drink/gi, '')
    .replace(/: Then drink the Soma juice expressed/gi, '')
    .replace(/Strong,,/g, 'Strong,')
    .replace(/up Enough/g, 'up enough')
    .replace(/: Still keep ye us victorious/g, '')
    .replace(/p:O BRĀHMAṆASPATI, make him who presses Soma glorious. /g, '')
    .replace(/Even Kakṣīvān Auśija./g, '')
    .replace(/,—may he be with us still/g, '')
    .replace(/Preserve us, Soma/g, '')
    .replace(/, Brahmaṇaspati/g, '')
    .replace(/, O Brahmaṇaspati, and/g, ' ')
    .replace(/, Dakṣiṇā, P/g, 'p')
    .replace(/in prayer/g, 'in meditation')
    .replace(/I have seen Narāśaṁsa, h/g, 'H')
    .replace(/Somapreserve/g, 'preserve')
    .replace(/, unfailing, that assist the rite/g, '')
    .replace(/ the lovely Night and Dawn/g, ',')
    .replace(/The two Invokers /g, '')
    .replace(/With Svāhā p/g, 'P')
    .replace(/Thither I call the Deities/g, 'We call the Devas')
    .replace(/Thither I call the Deities/g, 'We call the Devas')
    .replace(/, for thee these Soma drops have been prepared: Drink of them, hearken to/g, ', hear')
    .replace(/, with Soma juice poured forth/g, '')
    .replace(/ for the Soma draught/g, '')
    .replace(/ the Soma-presser/g, ' we')
    .replace(/Mitra and Varuṇa, t/g, 'T')
    .replace(/, have ye obtained your might power/g, '.')
    .replace(/Mitra, I call/g, 'We call')
    .replace(/, Mitra-Varuṇa/g, '')
    .replace(/glorify Thee/g, 'glorify thee')
    .replace(/, devourers of the foe/g, '')
    .replace(/ with the fatness dropping milk/g, '')
    .replace(/Young Rudras, demon-slayers, n/g, 'N')
    .replace(/The progeny of Rudra we invoke with prayer, t/g, 'T')
    .replace(/Ones To/g, 'Ones. To')
    .replace(/enriched with prayer/g, 'enriched with meditation')
    .replace(/, the youths of Rudra/g, '')
    .replace(/stain; The/g, '.')
    .replace(/, O Nodhas/g, '')
    .replace(/LIKE Aṅgiras a/g, 'A')
    .replace(/Praised by Aṅgirases, t/g, 'T')
    .replace(/, foe-destroyer, hast, with the Dawn, Sun, rays,/g, '')
    .replace(/, he parted of old the ancient Pair, united ever/g, '')
    .replace(/set both Dames and Earth and Heaven/g, 'set both Earth and Heaven')
    .replace(/, young Dames, each in her manner, unlike in hue, the Pair/g, '')
    .replace(/Night with her dark limbs/g, 'Night with dark limbs')
    .replace(/, Gotama's son Nodhas hath fashioned this new prayer to thee Eternal/g, '')
    .replace(/, when he slew the Dragon, the Dames, too/g, '')
    .replace(/ cut piece-meal Vṛtra, drier up of waters. H/g, ', h')
    .replace(/, victorious, for Turvīti/g, '')
    .replace(/, against this Vṛtra/g, '')
    .replace(/his joints, as of an ox, dissevered,/g, '')
    .replace(/, tremble for terror/g, '')
    .replace(/May Nodhas, e/g, 'E')
    .replace(/ Indra hath helped Etaśa, Soma-presser, contending in the race of steeds with Sūrya./g, '')
    .replace(/the Gotamas have brought their prayers to please thee/g, 'we have brought our offerings to thee')
    .replace(/Bestow upon them/g, 'Bestory upon us')
    .replace(/Priest/g, 'Monk')
    .replace(/As such we Gotamas with hymns extol thee, /g, '')
    .replace(/Banner of sacrifice/g, 'Banner of Offering')
    .replace(/treasure Mātariśvan/g, 'treasure')
    .replace(/Monk to Bhṛgu/g, 'Monk')
    .replace(/honey; Whom/g, 'honey. Whome')
    .replace(/priests/g, 'monks')
    .replace(/, Vaiśvānara,/g, '')
    .replace(/Vaiśvānara, the Deities/g, 'The Deities')
    .replace(/ whom Pūru's sons follow as Vṛtra's slayer:/g, '')
    .replace(/ struck down the Dasyu, cleave Śambara through and shattered down his fences/g, '')
    .replace(/, holy mid the Bharadvājas/g, '')
    .replace(/ by Purūṇītha, son of Śatavani/g, '')
    .replace(/ that Vasus, Rudras do, immortal/g, '')
    .replace(/\! when/g, '! When')
    .replace(/ deftest Sacrificer/g, '')
    .replace(/ the terrible/g, '')
    .replace(/, like bright Dawn/g, '')
    .replace(/, O Maghavan,/g, '')
    .replace(/shatterer wrought/g, 'wrought')
    .replace(/and drinks the Soma juice/g, '')
    .replace(/ wily Śushṇa/g, '')
    .replace(/Strength the Goddess/g, 'Strength')
    .replace(/When Strength/g, 'When strength')
    .replace(/as the Sun attends the Dawn/g, '')
    .replace(/then. he/g, 'then he')
    .replace(/unremoved, In/g, 'unremoved. In')
    .replace(/, thou smotest Vṛtra dead and/g, '')
    .replace(/ by the juiced/g, '')
    .replace(/, and broken Vṛtra's stony fences through and through/g, '')
    .replace(/Awful and very mighty, causing woe to men, h/g, 'H')
    .replace(/ to drink of Soma juice/g, 'H')
    .replace(/Drinker of Soma, let/g, 'Let')
    .replace(/, to this distressful fight/g, '')
    .replace(/: did not men run in crowds together in their fear\?/g, '.')
    .replace(/Thou helpest Narya, Turvaśa, and Yadu, and Vayya's son Turvīti, Śatakratu\!/g, '')
    .replace(/, be some who drink the Soma,/g, '')
    .replace(/: in Vṛtra's hollow side the rain-cloud lay concealed/g, '')
    .replace(/, O Conqueror,/g, '')
    .replace(/scattering the Dasyu through/g, 'scattering the seed through')
    .replace(/ freed from their hate/g, '')
    .replace(/, Soma draughts,/g, '')
    .replace(/, made bold by Soma draughts/g, '')
    .replace(/ upon the jaws of Vṛitra hard to be restrained/g, '')
    .replace(/ offeringr's/g, '')
    .replace(/ thou hadst slain with might the dragon Vṛtra,/g, '')
    .replace(/: thou from of old wast born to strike the Dasyus dead/g, '')
    .replace(/ when the Dasyus were struck dead/g, '')
    .replace(/; punishing the lawless/g, '')
    .replace(/, Soma-presser,/g, '')
    .replace(/pours the Soma, juice/g, 'pours the offering')
    .replace(/, ornaments of sacrifice,/g, '')
    .replace(/, drunk the Soma juice\./g, '.')
    .replace(/path of sacrifice/g, 'path of offering')
    .replace(/, who save when Soma gladdens them/g, 'path of offering')
    .replace(/, as to Manu erst;/g, '')
    .replace(/come to the Soma and our praise/g, 'come to our offering')
    .replace(/, the Rudras, the Ādityas, all Who spring from Manu/g, '')
    .replace(/Praskaṇva's call, as Priyamedha erst was heard, Atri, Virūpa, Aṅgiras/g, 'our call')
    .replace(/of Priyamedha/g, '')
    .replace(/ with Soma pressed have/g, 'have')
    .replace(/, the host of Heaven, juice/g, '.')
    .replace(/stands the Soma,/g, '')
    .replace(/: Here stands the Soma, bounteous Devas drink this expressed ere yesterday/g, '')
    .replace(/We pray/g, 'We meditate')
    .replace(/That Aditi may grant/g, 'That may grant')
    .replace(/charioteer of sacrifice/g, 'charioteer of offering')
    .replace(/granting to Praskaṇva/g, 'granting')
    .replace(/, at night, Uṣas and Savitar, the Aśvins, Bhaga/g, '')
    .replace(/, with Soma poured, the Kaṇvas light thee/g, '')
    .replace(/Lord of sacrifice and/g, 'Lord and')
    .replace(/, this day juice/g, '')
    .replace(/, the great high priest in sacrifice/g, '')
    .replace(/Like Manu, we/g, 'We')
    .replace(/; Let Mitra, Aryaman, seeking betimes our rite/g, '')
    .replace(/ May Law-supporting Varuṇa with the Aśvins twain and Uṣas, drink the Soma juice\./g, '')
    .replace(/wafting God\./g, 'wafting Deva')
    .replace(/O BRAHMAṆASPATI/g, 'O Soma')
    .replace(/ Varuṇa, Mitra, Aryaman/g, '')
    .replace(/What sacrifice,/g, 'What offering')
    .replace(/ Aryaman's and Mitra's laud, Glorious food of Varuṇa/g, 'glorious food')
    .replace(/four Within/g, 'four within')
    .replace(/cloud-born God/g, 'cloud-born Deva')
    .replace(/Devas Devas/g, 'Devas')
    .replace(/, Ādityas,/g, ' Devas')
    .replace(/ Ādityas, ye/g, 'ye')
    .replace(/prepareglorious/g, 'prepare glorious')
    .replace(/God-serving/g, 'Deva-serving')
    .replace(/the priest /g, 'the Monk ')
    .replace(/\? who the/g, '? Who the')
    .replace(/lap of Savitar,/g, 'lap of the')
    .replace(/gold-handed Devas/g, 'gold-handed Indra')
    .replace(/slew the Dragon, then/g, '')
    .replace(/e slew the Dragon lying on the mountain: h/g, '')
    .replace(/Impetuous as a bull, he chose the Soma and in three sacred beakers drank the juices\. /g, '')
    .replace(/Indra with his own great and deadly thunder smote into pieces Vṛtra, worst of Vṛtras\. /g, '')
    .replace(/, thou hadst slain the dragon's firstborn, and/g, '')
    .replace(/, like a mad weak warrior/g, '')
    .replace(/ with scattered limbs dissevered/g, '')
    .replace(/: Indra hath cast his deadly bolt against her/g, '')
    .replace(/, hast won the Soma;/g, ',')
    .replace(/for ever/g, 'forever')
    .replace(/ seeking strength with Soma-drops/g, '')
    .replace(/room Within/g, 'room within')
    .replace(/Slay each reviler, and d/g, 'D')
    .replace(/O SOMA DRINKER/g, 'O Indra')
    .replace(/ of beauteous horses and of kine/g, '')
    .replace(/evermore Protect/g, 'evermore protect')
    .replace(/better prayer/g, 'better offering')
    .replace(/that Āditya, very/g, 'that very')
    .replace(/Heaven Hear,/g, 'Heaven,')
    .replace(/loose The/g, 'loose the')
    .replace(/what hereafter will/g, 'what will')
    .replace(/ to mighty Aditi/g, '')
    .replace(/us Continually/g, 'us continually')
    .replace(/Agni the Deva the first/g, 'Indra, the first')
    .replace(/ Which Bhaga hath dealt out to us/g, '')
    .replace(/, sacrifices,/g, ',')
    .replace(/me meditation/g, 'my meditation')
    .replace(/he to whom prayed fettered Śunaḥśepa, may /g, '')
    .replace(/captured Śunaḥśepa thus to /g, '')
    .replace(/Marut hosts whom/g, 'hosts whom')
    .replace(/, Somas, for the fame Of Mitra, to the Soma-draught/g, '')
    .replace(/, with the Ādityas,/g, ',')
    .replace(/ to drink the milky draught /g, ' ')
    .replace(/, I pour the Soma-mingled meath:/g, ',')
    .replace(/Dear Narāśaṁsa/g, 'Dear Agni')
    .replace(/pour ye forth the juice, the active gladdening juice to him. T/g, 't')
    .replace(/ and Tvaṣṭar,H/g, '')
    .replace(/, Hotrā, Bhāratī, Varūtrī, Dhiṣaṇā,/g, '')
    .replace(/ on Viṣṇu's works,/g, ',')
    .replace(/, juice\./g, '.')
    .replace(/Viṣṇu, the/g, 'The')
    .replace(/p:Indrāṇī, Varuṇānī, and Agnāyī hither I invite, for weal,  juice./g, '')
    .replace(/yourselves Indra/g, 'yourselves, Indra')
    .replace(/offers Soma juice/g, 'offers')
    .replace(/gifts, is beautiful/g, 'gifts is beautiful')
    .replace(/hither, friends/g, 'hither friends')
    .replace(/whole Was/g, '')
    .replace(/vigilant, Lovers/g, 'vigilant. Lovers')
    .replace(/, Mitra-Indra,/g, '')
    .replace(/drink our libation/g, 'enjoy our offering')
    .replace(/, the Brahman finding wealth:/g, ',')
    .replace(/thou God/g, 'thou Deva')
    .replace(/sacrifice exalt/g, 'offerings exalt')
    .replace(/, vast Mātariśvan/g, '')
    .replace(/God\'s/g, 'Deva\'s')
    .replace(/give us kine and horses/g, 'give to us')
    .replace(/God who/g, 'Deva who')
    .replace(/a God with Devas/g, 'with Devas')
    .replace(/righteous blent with meath/g, 'righteous')
    .replace(/due is sacrifice/g, 'due is offerings')
    .replace(/With gay /g, 'With bright ')
    .replace(/eloquent, Perform/g, 'eloquent, perform')
    .replace(/I address, Sarasvatī, and Bhāratī, and Iḷā, all: U/g, 'u')
    .replace(/, preceder of the Devas,/g, '')
    .replace(/, Vanaspati/g, '')
    .replace(/sacrificial draught/g, 'sacred offering')
    .replace(/p:Tvaṣṭar the Lord hath made all forms and all the cattle of the field Cause them to multiply for us./g, '')
    .replace(/ he slew the Dragon/g, '')
    .replace(/, wax thou fat thereby/g, '')
    .replace(/, Vātāpi, grow thou fat thereby/g, '')
    .replace(/: Vātāpi, grow thou fat thereby/g, '')
    .replace(/our sacrificial gifts/g, 'our sacred gifts')
    .replace(/, these savours of thy juices work like creatures that have mighty necks/g, '')
    .replace(/, not unkind/g, '')
    .replace(/gifts, From/g, 'gifts. From')
    .replace(/ the Vṛtra-slayer/g, '')
    .replace(/, Aryaman, Mitra, Indra/g, ', Indra')
    .replace(/by the godly/g, 'by the Deva')
    .replace(/, destroyers of the foe allies of Mitra/g, '')
    .replace(/, armed with mighty weapons,/g, '')
    .replace(/, with hope to conquer, P/g, 'p')
    .replace(/Moreover Tvaṣṭar/g, 'Moreover Indra')
    .replace(/ flieth o’er all the barren soil their/g, '')
    .replace(/, and Pūṣan,/g, '')
    .replace(/, Vāta, and Ṛbhukṣan so may I bring/g, ' and')
    .replace(/, ye Holy;/g, ',')
    .replace(/,— Thought/g, '. Thought')
    .replace(/Nāsatyas, Pūṣans, ye as /g, '')
    .replace(/. may/g, '. May')
    .replace(/ subdue the niggards/g, '')
    .replace(/ Sūrya's bridal/g, '')
    .replace(/poet Māna/g, 'poet')
    .replace(/ by the Mānas/g, '')
    .replace(/, O Nāsatyas, in Agastya/g, '')
    .replace(/: Nāsatyas/g, '')
    .replace(/Monkis/g, 'Monk is')
    .replace(/, O Nāsatyas, Heroes/g, '')
    .replace(/Gotama, Purumīlha, Atri bringing/g, 'Bringing')
    .replace(/, ye Nāsatyas/g, '')
    .replace(/Let not the wolf, let not the she-wolf harm you. Forsake me not, nor pass me by or others\./g, '')
    .replace(/on. e/g, 'on e')
    .replace(/; make ye the niggard's life decay:/g, ',')
    .replace(/, both Nāsatyas,/g, ',')
    .replace(/fly withal,/g, 'fly.')
    .replace(/ for Tugra's son/g, '')
    .replace(/God-devoted/g, 'Deva-devoted')
    .replace(/, save the son of Tugra,/g, ',')
    .replace(/, longed for, succourers of Viśpalā/g, ',')
    .replace(/foes, O/g, '. O')
    .replace(/creatur\./g, 'creature.')
    .replace(/ by Mānas, F/g, ', f')
    .replace(/, like Pūṣan, Aśvins!/g, '')
    .replace(/Like Tugra's ancient so\. /g, '')
    .replace(/The prayer is that the Siste\. /g, '')
    .replace(/, all praised, meath-drinkers!/g, '')
    .replace(/, matured within her,/g, '')
    .replace(/, shining like a serpent mid trees,/g, '')
    .replace(/ for Atri at his wish/g, '')
    .replace(/: decayed for you is sorrow\'s net/g, '')
    .replace(/: he, like a pious man, gains strength for increase/g, '')
    .replace(/God is/g, 'Deva is')
    .replace(/, Agastya,/g, '')
    .replace(/, and give good horses to sacrificers/g, '')
    .replace(/, Nāsatyas\!/g, '')
    .replace(/cow, Which/g, 'cow. Which')
    .replace(/ to you whose form is perfect/g, ' to you')
    .replace(/Let not the Sovran Indra disappoint us in what shall bring both Sisters/g, ' Bring Sovran Indra')
    .replace(/supplication, Will/g, ' supplication. Will')
    .replace(/exalt u\./g, 'exalt you.')
    .replace(/, O Indra, O Indra/g, ', O Indra')
    .replace(/Indra. May/g, 'Indra, may')
    .replace(/,,/g, ',')
    .replace(/is God-reaching sacrifice/g, 'is the Deva-reaching offering')
    .replace(/here the victim; /g, '')
    .replace(/ Māna. Singing/g, '')
    .replace(/: with Soma/g, '')
    .replace(/,— Ascend thou these/g, '')
    .replace(/, here is the Soma\./g, '.')
    .replace(/, Śakra; seat thee and drink:/g, ', Indra, seat thee, ')
    .replace(/mighty Soma is poured/g, 'offerings are poured')
    .replace(/, are the prayers\./g, '.')
    .replace(/: come hither,\./g, ',')
    .replace(/thirsty, So u/g, 'thirsty. U')
    .replace(/Let our strong drink/g, 'Let our offering')
    .replace(/, Blameless!/g, ',')
    .replace(/, bear Kutsa,/g, ',')
    .replace(/, hast slain the vexers of thy friends, who give not/g, '')
    .replace(/, and to his home brought Kuyavāc to subdue him/g, '')
    .replace(/, thou keptest Turvaśa and Yadu safely/g, '')
    .replace(/, God-like,/g, '')
    .replace(/, the hosts agree beside the Soma,/g, ',')
    .replace(/S\. May/g, 'May')
    .replace(/with sacrifice they/g, 'with offerings they')
    .replace(/every sacrifice makes Indra/g, 'every offering makes Indra')
    .replace(/angry in spirit;/g, 'in spirit')
    .replace(/as serpents gleam/g, 'as diamonds gleam')
    .replace(/w. May/g, 'we may')
    .replace(/, Tṛṇskanda's folk; Lift/g, ' lift')
    .replace(/lift ye us/g, 'lift us')
    .replace(/favour A hymn/g, 'favour a hymn')
    .replace(/y whom the Mānas recognize the day-springs, b/g, '')
    .replace(/mornings, Give/g, 'mornings. Give')
    .replace(/rid thee of thy wrath against /g, '')
    .replace(/them, the wise, victorious/g, 'them the wise victorious')
    .replace(/\. fierce with the fierce, the/g, '. The')
    .replace(/\. Devas\./g, ', Devas.')
    .replace(/I fled in terror from this mighty Indra, my body trembling in alarm, /g, '')
    .replace(/Devas. Oblations meant for you had/g, 'Devas, offerings meant for you have')
    .replace(/aside: for this forgive us/g, 'aside')
    .replace(/ Why, O Indra, wouldst thou take our lives\?/g, '')
    .replace(/Agastya, brother, why dost thou neglect us, thou who art our friend\?/g, '')
    .replace(/: we two Here will spread sacrifice/g, ', we will prepare the offering')
    .replace(/, and do not subdue us in the fight/g, '')
    .replace(/thee, that the Immorta\. May observe\./g, 'the Immortal to observe.')
    .replace(/, and lost is then the hope we formed/g, '')
    .replace(/to the Mānas,/g, 'to')
    .replace(/That spear of thine sat firm for us, /g, '')
    .replace(/whole dread power/g, 'wole power')
    .replace(/, gifts of cattle foremost/g, '')
    .replace(/, who with their rush o’erthrow as ’twere a sinner the mortal who would fight with those who love him/g, '.')
    .replace(/: exert thee in the great terrestrial region; F/g, ', f')
    .replace(/, what time the Devas scatter forth their fatness/g, '')
    .replace(/, like Somas with their well-grown stalks pressed out,/g, '')
    .replace(/Pṛśni brought forth, to fight the mighty battle, t/g, 'T')
    .replace(/laud. May/g, 'laud, may')
    .replace(/, sung by the poet's son, Māndārya, Bring offspring for ourselves with/g, ' bring offering')
    .replace(/begat the monster, and then/g, '')
    .replace(/us, Now/g, '. Now')
    .replace(/ fierce Devas drave not Rodasī before them, but wished/g, ' Devas wished')
    .replace(/When chose immortal Rodasī to follow—she with loose tresses and heroic spirit— /g, '')
    .replace(/lauded, How/g, 'lauded. How')
    .replace(/Mitra and Indra they guard/g, 'Indra guards')
    .replace(/: Aryaman too, discovers worthless sinners/g, '.')
    .replace(/sung by the poet, Māna's son, Māndārya, Bring offspring for ourselves with /g, 'bring ')
    .replace(/, Mitra, Indra/g, ', Indra')
    .replace(/ which the Steeds' Lord ever visits,/g, '')
    .replace(/, from the hated demon/g, '')
    .replace(/the. May/g, 'the, may')
    .replace(/pour blessings on our chiefs and nobles/g, 'pour blessings on us')
    .replace(/Condemn us not to indigence, /g, '')
    .replace(/; Nor, even after fault, let thy displeasure, thine as a Deva/g, '')
    .replace(/would kill us/g, 'would harm us')
    .replace(/: with Indra leading,/g, ', with Indra leading,')
    .replace(/, of goodly aspect,/g, ', of heroic nature,')
    .replace(/Deva and asking him for riches/g, 'Deva')
    .replace(/p:joined/g, 'p:Joined')
    .replace(/worship an unwearied envoy/g, 'praise and adoration')
    .replace(/, like the Dawn's Lover,/g, '')
    .replace(/, Soma All-bounteous, with the Singers/g, '')
    .replace(/, ne.'er deceived, uncircumscribed, refulgent/g, '')
    .replace(/, forcing doors of Paṇis,/g, '')
    .replace(/a Friend/g, 'a friend')
    .replace(/, Shines/g, '. Shines')
    .replace(/: the kine have waked to meet him when enkindled/g, '')
    .replace(/who pray and worship/g, 'who meditate and make offerings')
    .replace(/ that the, may give us riches, Sarasvatī, the Devas/g, '')
    .replace(/Vasiṣṭha, when enkindling thee, O Agni, hath slain jarutha. /g, '')
    .replace(/Give us wealth in plenty. /g, '')
    .replace(/, the Vasisthas,/g, '')
    .replace(/to singers and to nobles/g, 'to us')
    .replace(/he who knoweth he/g, 'he')
    .replace(/, Brahman,/g, ',')
    .replace(/, He/g, '. He')
    .replace(/Heaven anct Earth/g, 'Heaven and Earth')
    .replace(/strengthenwhom/g, 'strengthen whom')
    .replace(/, Giver of all boons,/g, '')
    .replace(/; Who/g, '. Who')
    .replace(/, high imperial Ruler/g, '')
    .replace(/- I laud his deeds who is as strong as Indra,/g, ', we laude his deeds,')
    .replace(/, and lauding celebrate the Fort-destroyer/g, '')
    .replace(/,—they bring him from the mountain,/g, ',')
    .replace(/, fort-destroyer,/g, ',')
    .replace(/rudely-speaking niggards/g, 'rudely-speaking')
    .replace(/, O bright as Mitra,/g, '')
    .replace(/Wherewith, all/g, 'Wherewith all')
    .replace(/spreading, on/g, 'spreading on')
    .replace(/upon our chiefs and nobles/g, 'upon us')
    .replace(/, of his Mother;/g, '.')
    .replace(/God-made/g, 'Deva-made')
    .replace(/Agni is Lord of Amṛta. in abundance, Lord/g, 'Agni is Lord')
    .replace(/The foeman's treasur. May be won with labour. /g, '')
    .replace(/Here let the place of darkening come upon thee. /g, '')
    .replace(/, O Agni; O Deva,/g, ', O Agni,')
    .replace(/, Aṅgiras' son,/g, ',')
    .replace(/, the great stalls filled with cattle/g, '')
    .replace(/: ye killed all darkness and the Devas’ blasphemers/g, '')
    .replace(/, gave her light to Morning, and/g, ', ')
    .replace(/, and spread abroad apart, the Earth, the Mother/g, ', ')
    .replace(/slew the flood -obstructing serpent Vṛtra,/g, ', ')
    .replace(/Indra and Soma:/g, 'Indra and Soma,')
    .replace(/, thou,/g, '')
    .replace(/Drink of this meath, O Indra and Indra; drink ye your fill of Soma, Wonder-Workers. /g, '')
    .replace(/The sweet exhilarating juice hath reached you./g, '')
    .replace(/, Indra and Indra,/g, '')
    .replace(/, IndraIndra,/g, ',')
    .replace(/worship ana/g, 'joy ana')
    .replace(/, Fed with the holy oil, vouchsafe us riches ye are the lake, the vat that holds the Soma/g, '')
    .replace(/, to the Soma\./g, '.')
    .replace(/the offering and grant us riches/g, 'these offerings')
    .replace(/hymns ye vessels who contain the Soma juices, May/g, 'hymns, may')
    .replace(/p:Ye Twain have conquered, ne’er have yc been conquered: never hath either of the Twain been vanquished. Ye, Indra, when ye fought the battle, produced this infinite with three divisions./g, '')
    .replace(/ foe-conquering horses/g, 'horses')
    .replace(/meditations and/g, 'meditations, and')
    .replace(/gifts and offers/g, 'gifts and offerings')
    .replace(/(\b)Indra. and Indra, Devas(\b)/g, '$1Indra and IndraDeva$2')
    .replace(/(\b)Indra and Indra(\b)/g, '$1Indra and IndraDeva$2')
    .replace(/, drinkers of the juice, drink this pressed Soma which shall give you rapturous joy. Y/g, ', y')
    .replace(/, This juice is shed by us that y. May quaff it: on this trimmed grass be seated, and rejoice you/g, '')
    .replace(/, by Law made Vṛtra's slayers/g, '')
    .replace(/ subdues Vṛtra;/g, '')
    .replace(/mingle ye wealth with our/g, 'with your')
    .replace(/, sublime, imperial Lord/g, '')
    .replace(/- They/g, '. They')
    .replace(/this invigorating sweetest Soma/g, 'this invigorating sweetest hymn')
    .replace(/ by us that y. May quaff it: /g, ' ')
    .replace(/, wherewith of old thou burntest up Jarutha/g, '')
    .replace(/: widely ye strode in the wild joy of Soma/g, '')
    .replace(/you($)/g, 'you.$1')
    .replace(/, and rejoice you/g, ', and rejoice you.')
    .replace(/rain-pouring Soma/g, 'rain')
    .replace(/whose germ great Mother Pṛśni is/g, 'offerings')
    .replace(/quickly wins for milking/g, 'quickly wins')
    .replace(/, the brood of Soma,/g, ',')
    .replace(/have the Soma streamed/g, 'have the Indu streamed')
    .replace(/: When bIent, in waters they are rinsed/g, '')
    .replace(/The milk hath run to meet them like/g, 'Like')
    .replace(/O Soma Pavamana,/g, 'O Indu')
    .replace(/joy, O Soma, flow,/g, 'joy, O Indu, flow,')
    .replace(/, best Vṛtra-slayer;/g, ',')
    .replace(/the Soma of the meath eflused, Slayer of sinners/g, 'Indu')
    .replace(/the Indu streamed, the drops/g, 'the drops')
    .replace(/: The men have seized and lead thee forth/g, '')
    .replace(/POUR hitherward, O Soma,/g, 'POUR hitherward, O Indu,')
    .replace(/, Soma hath flowed into the jar: May Soma find it rich in sweets/g, ', Indu hath flowed')
    .replace(/These Somas swift and brown of hue, in/g, ', In')
    .replace(/Soma thou flowest chasing foes and /g, 'Indu flows')
    .replace(/: Drive off the folk who love not Devas/g, 'Bring the folk who love the Devas')
    .replace(/, the brilliant drops of Soma juice,/g, '')
    .replace(/, the beautiful swift Soma-drops, D/g, ', d')
    .replace(/From. Heaven/g, 'From Heaven')
    .replace(/effused Upon/g, 'effused upon')
    .replace(/O Soma, Indu,/g, 'O Indu,')
    .replace(/stream All/g, 'stream all')
    .replace(/, with thy stream All foes, all Rākṣasas away/g, '')
    .replace(/Driving the Rākṣasas afar, O Soma, bellowing,/g, 'O Indu,')
    .replace(/us Most/g, 'us most')
    .replace(/, O Soma, on thy way, Pressed out for Indra, for his drink/g, ', O Indu')
    .replace(/e thou best Vṛtra-slayer, b/g, '')
    .replace(/low onward with thy juice/g, 'low onward')
    .replace(/fleec\./g, 'fleece.')
    .replace(/: Flow hither for our strength and fame/g, '')
    .replace(/day: To/g, 'day. To')
    .replace(/ May Sūrya's Daughter purify Thy Soma that is foaming forth./g, '')
    .replace(/Ten sister maids of/g, 'The')
    .replace(/ seize him within the press and hold Him/g, ' hold him')
    .replace(/p:The virgins send him forth: they blow the the skin musician-like and fuse The triple foe-repelling meath./g, '')
    .replace(/milch-kine round about him blend /g, '')
    .replace(/fresh young Soma with their milk/g, 'fresh young Indu')
    .replace(/, Indra subdues all the Vṛtras:/g, ',')
    .replace(/Fiend-queller, Friend of all men/g, 'Friend of all men')
    .replace(/ To thee alone our meditations are said/g, '')
    .replace(/ the wild raptures of/g, '')
    .replace(/Soma, flow on, inviting Devas/g, 'Indu, flow on, inviting Devas')
    .replace(/well-loved meath was made to flow/g, 'well-loved was made to flow')
    .replace(/ ne Sage/g, '')
    .replace(/, when thou wilt clothe thee with the milk/g, '')
    .replace(/floods. Soma, our Friend./g, 'floods.')
    .replace(/, fair as mighty Mitra to behold: H/g, ', H')
    .replace(/wherewith Thou/g, 'where thou')
    .replace(/we pray,/g, 'we meditate,')
    .replace(/, to win the joyous draught:/g, '.')
    .replace(/praise&/g, 'praises')
    .replace(/bestows Rich/g, 'bestows rich')
    .replace(/across The/g, 'across the')
    .replace(/this God/g, 'this Deva')
    .replace(/, Effused,/g, '')
    .replace(/along Is/g, 'along is')
    .replace(/gifts: He/g, 'gifts. He')
    .replace(/bestows rich/g, 'bestows')
    .replace(/regions, into/g, 'regions into')
    .replace(/flowing, meet for offering,/g, 'flowing,')
    .replace(/the \'way/g, 'the way')
    .replace(/pressed out for Deities, Flows/g, 'pressed out flows')
    .replace(/O Soma flowing/g, 'O Indu, flowing')
    .replace(/; And make/g, 'renown. Make')
    .replace(/: Make thou us better/g, '. Make us better')
    .replace(/; Make thou us better/g, '. Make us better')
    .replace(/; And mate us better/g, '. Make us better')
    .replace(/to usa stream/g, 'to us a stream')
    .replace(/, bring us wealth in steeds,/g, ', bring us true wealth,')
    .replace(/power. O Soma, drive/g, 'power. O Indu, drive')
    .replace(/felicitiesrenown/g, 'felicities renown')
    .replace(/foesrenown/g, 'foes renown')
    .replace(/, drive away our foesrenown\. M/g, ', m')
    .replace(/, purify Soma for Indra,/g, '')
    .replace(/aidsrenown/g, 'aids renown')
    .replace(/usrenown/g, 'us renown')
    .replace(/greatrenown/g, 'great renown')
    .replace(/ power\. O Indu, drive away our foes renown\./g, ' power, O Indu.')
    .replace(/, win thou and conquer high renownrenown/g, '')
    .replace(/, and, Soma, all felicities renown/g, '')
    .replace(/ through thine own mental power and aids renown/g, '')
    .replace(/aid lon. May/g, 'aid may')
    .replace(/Pavamana! men have strengthened thee to prop the Law./g, 'Pavamana!')
    .replace(/manifold. quickening/g, 'manifold, quickening')
    .replace(/unsubdued in battle pour forth wealth to us renown/g, 'unsubdued in battle')
    .replace(/Well-weaponed Soma, pour to us/g, 'Pour to us')
    .replace(/: thou art the Brahman,/g, ',')
    .replace(/ and aid may we look upon the Sun/g, '')
    .replace(/By worship,/g, 'With offerings,')
    .replace(/is worshipped, God/g, 'is honored, Deva')
    .replace(/three beauteous Goddesses, Sarasvatī and Bhāratī and Iḷā, Mighty One,/g, '')
    .replace(/1 summon Tvaṣṭar hither, our protector, champion earliest-born,/g, '')
    .replace(/, tawny Steer;/g, ',')
    .replace(/streams anoint Vanaspati,/g, ',')
    .replace(/Indu is Indra, Indu is Prajāpati./g, 'Indu is Indra.')
    .replace(/Soma, Sūrya, Soma, Indra, and Agni, in accord\./g, 'Soma, Indra, and Agni in accord.')
    .replace(/formed Like beauteous maidens,/g, 'formed like')
    .replace(/, Celestial Heralds:/g, ', Celestial Heralds,')
    .replace(/Indra's Self Is Indu, yea, the Bull/g, ', Indra\'s Self is Indu')
    .replace(/in , the/g, 'in, the')
    .replace(/, with the meath in, the ever-green. the golden-hued,/g, ', the ever-green, the golden-hued,')
    .replace(/Indu, Self/g, 'Indu, self')
    .replace(/SOMA, flow on/g, 'Indu, flow on')
    .replace(/, a Bull devoted/g, ',')
    .replace(/, and send us coursers full of strength/g, '')
    .replace(/descent They/g, 'descent, they')
    .replace(/ ten dames cleanse, as ’twere a vigorous steed,/g, '')
    .replace(/The steer-strong juice with milk pour forth, for feast/g, 'The juice pour forth, for offering')
    .replace(/Deva, So/g, 'Deva, so')
    .replace(/mil. May/g, 'will may')
    .replace(/on: he keeps His/g, 'on, he keeps his')
    .replace(/, strong drink,/g, ',')
    .replace(/for the feast, Thou, even in secret, storest hymns./g, 'For the banquet, even in secret, he storest hymns.')
    .replace(/, Knowing/g, ', knowing')
    .replace(/sinks the stream of meath/g, 'sinks the stream')
    .replace(/excellent, Oblation/g, 'excellent, oblation')
    .replace(/, What/g, ', what')
    .replace(/, the Steer true/g, ', the true')
    .replace(/round, the Strong/g, 'round the strong')
    .replace(/, what time the sages bring him nigh/g, '')
    .replace(/wood: The Singer/g, 'wood.\np:The Singer')
    .replace(/He goes to Indra, Soma, to the Aśvins,/g, 'He goes to Indra,')
    .replace(/Tle streams of pleasant Soma flow to Bhaga— /g, '')
    .replace(/riches of meath to win us wealth: Gain/g, 'gain')
    .replace(/ these Soma juices have flowed forth/g, '')
    .replace(/, In/g, ', in')
    .replace(/, we clothe thee with a robe of milk To/g, ' to')
    .replace(/When purified within the jars, brightred and golden-hued/g, '')
    .replace(/, Hath clothed him with a robe of milk/g, '')
    .replace(/ Give us, O Soma, victory in war\./g, '')
    .replace(/(\b)indra(\b)/g, '$1Indra$2')
    .replace(/, Gain thee, and progeny and food/g, '')
    .replace(/: the fount Hath satisfied the Goddesses/g, '.')
    .replace(/, Even Indu,/g, ', Indu,')
    .replace(/O Man: O Indu/g, 'O Indu')
    .replace(/evermore: Make/g, 'evermore. Make')
    .replace(/, give kine and steeds and hero sons: Win/g, ', win')
    .replace(/, have Soma-drops flowed/g, ', have drops flowed')
    .replace(/The Somas deck themselves with milk, as/g, 'The Kings')
    .replace(/, and, with seven monks, the/g, ', and with seven monks the')
    .replace(/, the Soma juices/g, ', the juices')
    .replace(/Winning Vivasvān's glory and p/g, 'P')
    .replace(/, Fill/g, ', fill')
    .replace(/eye: The Sage's ofrspring hath appeared/g, 'eye. The Sage\'s offspring hath appeared')
    .replace(/monks Have/g, 'monks have')
    .replace(/, Fain/g, ', fain')
    .replace(/to pay worship/g, 'to make offerings')
    .replace(/ the Atharvans have commingled milk/g, '')
    .replace(/Weal, O thou King, to growing plants/g, 'Weal, O King, to growing plants.')
    .replace(/to Soma brown of hue/g, 'to Indu')
    .replace(/The Red, who reaches up to Heaven/g, 'The Blue, who reaches up to Heaven')
    .replace(/Purify Soma when effused/g, 'Purify when effused')
    .replace(/, and pour the sweet milk in the meath/g, '')
    .replace(/; blend the libation with the curds:/g, '.')
    .replace(/Soma, foe-que chief o’er men, doing/g, 'Indu, doing')
    .replace(/forth Prosperity/g, 'forth prosperity')
    .replace(/O Soma, that Indr. May/g, 'O Indu, that Indra may')
    .replace(/Indu! with. Indra for ally./g, 'Indu! with Indra for his ally.')
    .replace(/p:Purify when effused with stones which bands move rapidly./g, '')
    .replace(/To Indra have the Soma drops, exceeding rich in sweets,/g, 'To Indra have the drops')
    .replace(/As mother kine low to their calves, t/g, 'T')
    .replace(/\, Called him  juice/g, '')
    .replace(/wave wise Soma dwells/g, 'wave wise Indu dwells')
    .replace(/, Resting upon a wiId-cow's hide/g, '')
    .replace(/Far-sighted Soma, Sage and Seer,/g, 'Indu')
    .replace(/, the straining-cloth of wool/g, '')
    .replace(/, Urging men\'s generations on/g, '')
    .replace(/, the Soma urged to speed, flows on To/g, ', flows on to')
    .replace(/p:In close embraces Indu holds Soma when poured within the jars\./g, '')
    .replace(/And on the. purifying sieve\./g, '')
    .replace(/Soma, as thou art purified, incite/g, 'Indu, incite')
    .replace(/on: The/g, 'on. The')
    .replace(/p:When purified within the jars, Soma, brightred and golden-hued\./g, '')
    .replace(/ on to Soma and the Aśvins. May These/g, ', ')
    .replace(/us rich. Drive all our enemies away/g, 'us wealthy')
    .replace(/thy Friend. Send/g, 'thy friend, send')
    .replace(/O Vṛtra-slayer,/g, 'O Indra,')
    .replace(/or niggard brother/g, 'or brother')
    .replace(/, O friends;/g, ', O Friends,')
    .replace(/mighty Indra when the juice is shed/g, 'might Indra')
    .replace(/lauds repeatedly:/g, 'lauds repeatedly.')
    .replace(/, like a bull who rushes down, men's Conqueror, bounteous like a cow; Him/g, '')
    .replace(/both, of enmity and peace/g, 'both of enmity and peace')
    .replace(/meditation addressed/g, 'both of enmity and peace')
    .replace(/that i. May/g, 'that he may')
    .replace(/succour/g, 'assist')
    .replace(/O Caster of the Stone,/g, 'O Indra,')
    .replace(/, Not for a thousand/g, '')
    .replace(/ nor ten thousand, nor a hundred,/g, '')
    .replace(/, O Good Lord/g, ', O Indra')
    .replace(/to give me/g, ', to give us')
    .replace(/psalm to him who breaks down castles/g, 'song to him')
    .replace(/Thou and my mother, O Indra, appear alike,/g, 'O Indra,')
    .replace(/ destroy the forts and/g, '')
    .replace(/, Verses/g, ', hymns')
    .replace(/sit on Kaṇva's/g, ', sit on')
    .replace(/ Sabardughā who animates/g, '')
    .replace(/the richly-yielding Milch-cow/g, '')
    .replace(/hen Sūra wounded Etaśa, w/g, '')
    .replace(/ bore Kutsa Ārjuneya off, and mocked Gandharva\./g, ',')
    .replace(/, before making incision in the neck, C/g, ' c')
    .replace(/, count ourselves as trees rejected and unfit to burn/g, ', count ourselves as friends')
    .replace(/bount. May we have delight/g, 'bount')
    .replace(/the, may out Soma-drops that flow Rapidly through the strainer gladden/g, '')
    .replace(/ drops due to the Tugryas\’/g, '')
    .replace(/May our wealthy nobles’/g, 'May our')
    .replace(/ out the Soma with the stones, and in/g, 'May our')
    .replace(/ The men investing it with raiment made of milk shall milk it forth from out the stems\./g, '')
    .replace(/, Wax/g, ', wax')
    .replace(/car. Indra,/g, 'car, Indra,')
    .replace(/PressMay/g, 'May')
    .replace(/For India press the Soma out, m/g, 'M')
    .replace(/drink: for/g, 'drink, for')
    .replace(/he in ecstasy/g, 'he')
    .replace(/Śuṣṇa's quick moving castle thou hast crushed to pieces with thy bolts. Thou/g, 'In the quick moving castle')
    .replace(/, since we have had thee to invoke/g, '')
    .replace(/night, O Vasu, have/g, 'night, O Indra, have')
    .replace(/ Of princes these are the most liberal of their gifts, .+? Medhyātithi./g, '')
    .replace(/- For skilled is Yadu's son .+ rich in herds of kine/g, '')
    .replace(/, May/g, ', may')
    .replace(/ and turn not from/g, ' and hear')
    .replace(/, I yoked/g, ', he yoked')
    .replace(/who gave me two brown steeds together with their/g, 'with their')
    .replace(/, May he, Āsaṅga's son Svanadratha,/g, '')
    .replace(/p:Playoga's son Āsaṅga, by ten (.+) upstanding./g, '')
    .replace(/ her husband\'s/g, ' his')
    .replace(/, His consort Śaśvatī with joy addressed him, N/g, ', n')
    .replace(/manhood was apparent/g, 'manhood')
    .replace(/May Narāśaṁsa lighting up the chambers, b/g, 'B')
    .replace(/, Steeping the gift with oil diffusing purpose,/g, '')
    .replace(/, as is thy right,/g, ',')
    .replace(/Bring thou the Marut host. /g, ',')
    .replace(/O Grass divine,/g, 'O Indra,')
    .replace(/Doorsdesses/g, 'door')
    .replace(/Indra-Soma/g, 'Indra and Soma')
    .replace(/, have been shed;/g, ',')
    .replace(/come for our offered dainties’ sake:/g, 'we invite you to our offeirngs.')
    .replace(/prepared: Soon. /g, 'prepared, ')
    .replace(/thus I make my/g, 'thus we make our')
    .replace(/, and foe-destroying/g, ', Soma and')
    .replace(/Mitra and Indra, through Law, lovers and cherishers of Law./g, 'Soma and Indra, through Law, lovers and cherishers of Law.')
    .replace(/, Lords of splendour,/g, '')
    .replace(/, ye heroes worthy of our praise,/g, '')
    .replace(/, Of the libation-pouring priest/g, '')
    .replace(/, as milch-kine hasten to their stalls/g, '')
    .replace(/down: to Indra sing ye forth, your song/g, 'down, Indra sing your song')
    .replace(/excellent, Indra, with Soma/g, 'excellent, Indra')
    .replace(/Whose pair of tawny horses yoked in battles foemen challenge not: /g, '')
    .replace(/O COME ye hither,/g, 'O Indra,')
    .replace(/Nigh to Soma come, f/g, 'F')
    .replace(/lover of the song. May/g, 'lover of the song, may')
    .replace(/\np:Nāsatyas, wonder-workers, yours are these libations with clipt grass: Come ye whose paths are red with flame./g, '')
    .replace(/\np:Approach, O Indra, hasting thee,/g, ' Approach, O Indra, hasting thee,')
    .replace(/, O men:/g, '')
    .replace(/side: Both/g, 'side, both')
    .replace(/Heaven: Our/g, 'Heaven. Our')
    .replace(/, at each strain of mine,/g, ',')
    .replace(/the Friend who bends his bolt at fiends\./g, 'the Friend.')
    .replace(/rise: I find no laud/g, 'rise, we find every song')
    .replace(/Even as the bull drives on the herds, h/g, 'H')
    .replace(/the Ruler irresistible:/g, 'the ruler irresistible.')
    .replace(/ away from other men: Ours, and none others’. May he be/g, '')
    .replace(/, and delight thee with the juice at all the Soma feasts/g, '')
    .replace(/p:To Indra the gladdening, omnific God./g, '')
    .replace(/ the praise-worthy who cometh to our aid/g, '')
    .replace(/(\b)God(\b)/g, '$1Deva$2')
    .replace(/, like a bay steed for war,/g, '')
    .replace(/, like a warrior going forth with heroes,/g, '')
    .replace(/, inviolable as/g, '')


    // SACRIFICE STRINGS
    .replace(/(\b)Sacrificer(\b)/g, '$1Offerer$2')
    .replace(/(\b)sacrificer(\b)/g, '$1offerer$2')

    .replace(/(\b)Sacrificers(\b)/g, '$1Creators$2')
    .replace(/(\b)sacrificers(\b)/g, '$1creators$2')

    .replace(/(\b)Sacrificed(\b)/g, '$1Offered$2')
    .replace(/(\b)sacrificed(\b)/g, '$1offered$2')

    .replace(/(\b)Sacrifices(\b)/g, '$1Offers$2')
    .replace(/(\b)sacrifices(\b)/g, '$1offers$2')

    .replace(/(\b)Sacrificest(\b)/g, '$1Offering$2')
    .replace(/(\b)sacrificest(\b)/g, '$1offering$2')

    .replace(/(\b)Sacrifice(\b)/g, '$1Offering$2')
    .replace(/(\b)sacrifice(\b)/g, '$1offering$2')

    .replace(/Soul of offering/g, 'Soul of Offerings')
    .replace(/this offering's/g, 'the offerings')

    .replace(/\,\—/g, '.')
    .replace(/\,\,/g, ',')
    .replace(/\, \, /g, ', ')
    .replace(/\,\./g, '.')
    .trim();

  const invoke = [
    'Indu',
    'Agni',
    'Aṅgiras',
    'Soma',
    'Indra',
    'Vāyu',
    'Mitra',
    'Varuṇa',
    'Aśvins',
    'Nāsatyas',
    'Viśvedevas',
    'Śatakratu',
    'Śakra',
    'Kuśika',
    'Śuṣṇa',
    'Narāśaṁsa',
    'Tvaṣṭar',
    'Svāhā',
    'Ṛtu',
    'Neṣṭar',
    'Dakṣiṇā',
    'Narāśaṁsa',
    'Maruts',
    'Ṛbhus',
    'Ādityas',
    'Savitar',
    'Hotrā',
    'Bhāratī',
    'Varūtrī',
    'Dhiṣaṇā',
    'Visnu',
    'Pūṣan',
    'Vamra',
    'Uśanā',
    'Indu',
    'Jātavedas',
    'Bhaga',
    'Sūnṛtā',
    'Vivasvān',
    'Māna',
    'Bhārata',
    'Vasisthas',
    'Aduras',
    'Rodasl',
    'Vamraka'
  ];

  const describeStr =/^p:(.+?[.|?|;|!])/;
  const describe = describeStr.exec(cleaned) ? describeStr.exec(cleaned)[1].trim() : false;

  const deities = [];

  const omatch = cleaned.match(/\b(O\s.{3,}?)(\b)/gi);
  if (omatch) omatch.forEach(om => {
    const dindex = deities.findIndex(item => item.name.toLowerCase() == om.toLowerCase());
    if (dindex === -1) {
      deities.push({
        name: om,
        hymns: [{key,title}]
      })
    }
    else {
      deities[dindex].hymns.push({key,title})
    }
  });

  return {
    key,
    title,
    describe,
    feecting: cleaned,
    meta: {
      next: nxt,
      previous: prv,
      book:bki,
      original: `https://sacred-texts.com/hin/rigveda/rv${key}.htm`,
      sanskrit: `https://sacred-texts.com/hin/rvsan/rv${key}.htm`,
    },
    deities,
  };
}
